-- ============================================================================
-- Script:    0041_mac533_ipvm_public_directory_attribution_ingest.sql
-- Status:    APPLIED 2026-07-28 (MAC-533 Phase 2 of v1.7.0 consolidated release).
--            Do NOT re-apply — see WARNING below.
--
-- WARNING: NOT RE-APPLY-SAFE (MAC-535, ratified by DBArchitect 2026-07-28).
-- The six `UPDATE manufacturers SET aliases = ...` statements on id=209
-- (Hikvision) lack a UNIQUE backstop, so a second apply would re-append
-- the 6 new tokens (EZVIZ, HiLook, Hikmicro, HiWatch, Annke, LaView)
-- producing `{'EZVIZ': 2, 'HiLook': 2, ...}` duplicates. Root cause:
-- the sqlite3 CLI does not -bail by default, so a failing `CHECK(ok=1)`
-- on the _mig0041_pre TEMP table aborts only the offending statement,
-- not the script. The 84 INSERTs and the sources INSERT are UNIQUE-
-- backstopped (canonical_name UNIQUE / sources.url NOT-NULL+UNIQUE), so
-- they survive; the UPDATE alone is unsafe on re-apply.
--
-- Mitigation if a re-apply ever becomes operationally necessary:
-- (a) read this file's pre-condition guard at line ~103 and confirm the
--     CHECK(ok=1) conditions fire (in particular condition (d): the 6
--     tokens must already NOT appear in Hikvision's aliases), OR
-- (b) wrap each `UPDATE ... SET aliases = CASE WHEN aliases NOT LIKE
--     '%<token>%' THEN ... END` so the append is idempotent on re-apply.
-- The current file is preserved verbatim to maintain the provenance link
-- between the migration file and what actually ran at apply time; do not
-- edit the body in place. If a corrective migration is needed, land it
-- as a new slot (mig-0043+) per §11 #21 (canonical-slot discipline) and
-- §11 #11 (amendment-log discipline).
--
-- Slot 0041 is free — verified by direct working-
-- tree read (highest live = 0039, MAC-528; git status --porcelain
-- db/migrations/ empty pre-author). Slot 0040 is RESERVED for
-- MAC-531 and is NOT touched here. schema_version stays at 33
-- (data-only attribution ingest; no DDL — no new CHECK enum value,
-- no column add, no rebuild).
--
-- Issue:     MAC-533 (Phase 2 of MAC-530 v1.7.0 consolidated release) — IPVM
--            public-directory attribution ingest.
--
-- Purpose:   Ingest the RATIFIED MAC-525 IPVM public-directory cohort as
--            attribution metadata into canonical db/argus.db:
--              * ONE sources row for the IPVM public directory (source_type
--                'crowdsourced' — existing CHECK-enum value, same slot as
--                FoggedLens/identification-catalog id=104 and fccid.io id=51;
--                justify: third-party public-attribution catalog, NOT vendor-
--                controlled / regulatory / primary_registry / procurement).
--              * SIX alias appends to manufacturers.id=209 (Hikvision) for
--                pure sub-brands and pure rebrands: EZVIZ, HiLook, Hikmicro,
--                HiWatch (Hikvision-owned per IPVM sub-brand cite) + Annke,
--                LaView (pure rebrand rubric per MAC-533 issue body).
--              * TWO parent-link UPDATEs on existing rows: Amcrest (id=298)
--                and Lorex (id=303) → Dahua (id=208) per current IPVM OEM
--                attestation. Speco (id=308) is LEFT UNTOUCHED — IPVM lists
--                Speco under Dahua (former/removed) and MAC-525 ratification
--                §"HOLD" explicitly forbids auto-attributing Speco to Dahua.
--              * FIFTY-TWO new SPOKE manufacturers rows under Hikvision 209
--                (is_arm=1, query_default='hidden_arm', parent_manufacturer_id
--                =209) for independent firms sourcing the Hikvision OEM line.
--              * THIRTY-TWO new SPOKE manufacturers rows under Dahua 208
--                (same shape) for independent firms sourcing the Dahua OEM
--                line.
--
-- Cohorts NOT ingested (per ingest_plan.md §1.C / §1.D):
--              * 44 Dahua (former/removed) OEM brands — HOLD. Major
--                independent brands (Panasonic, FLIR, IndigoVision, Legrand,
--                Speco, Tyco, ADT, etc.) MUST NOT be auto-attributed to Dahua
--                per MAC-525 ratification §"HOLD".
--              * 242 distinct vendor-name leads from vendor_leads.csv — LEADS
--                only; zero ingested in this phase. They seed SourceWorker's
--                downstream FCC/firmware pipeline.
--
-- Net-new identifier rows: ZERO (no INSERT or UPDATE on identifiers).
--
-- Notes JSON discipline (0038/0039 precedent, §11 #17): every new INSERT
-- builds notes via json_object(...) — always valid by construction. The 3
-- UPDATE targets (Amcrest 298 / Lorex 303 / Speco 308) have notes LEFT
-- UNTOUCHED; pre-flight sweep:
--              SELECT id, json_valid(notes) FROM manufacturers WHERE id IN (298,303,308);
--              298|1   303|1   308|1
-- All three pass; the UPDATEs only set parent_manufacturer_id (Amcrest/Lorex)
-- or do nothing (Speco). No text-suffix concat, no json_set merge.
--
-- Re-apply safety: TEMP TABLE _mig0041_pre blocks the second run unless
-- (a) Hikvision 209 / Dahua 208 / Uniview 255 are present as hubs, (b) the 3
-- already-covered UPDATE targets still have parent_manufacturer_id IS NULL,
-- (c) no manufacturer row has parent_manufacturer_id IN (208, 209, 255) yet,
-- (d) Hikvision aliases doesn't already contain any of the 6 new tokens,
-- (e) no sources row matches the IPVM public URL yet, (f) schema_version=33.
-- Any of these failing → CHECK(ok=1) constraint on the TEMP table fails →
-- transaction rolls back. A second apply aborts rather than double-writing.
--
-- Migration-slot allocation:
--   0038 = MAC-527 ssid_pattern FP-magnet refine/demote
--   0039 = MAC-528 Flock glob ssid_exact withdraw
--   0040 = (reserved for MAC-531 — NOT touched)
--   0041 = MAC-533 IPVM public-directory attribution ingest — THIS MIGRATION
--   0042 = (open; reserved for MAC-534 consolidated regen or future)
--
-- Bible:     §11 #1  no fabrication — every spoke row carries an IPVM
--                  source_url + cite_line JSON, no synthetic identifiers.
--            §11 #5  Phase boundaries respected — this is a v1.7.0 Phase 2
--                  (consolidated release) attribution ingest; no schema
--                  mutation, no identifier writes.
--            §11 #7  no main-table promotion without provenance — source_url
--                  NOT NULL on manufacturers (bible §4.4) is honored for
--                  every new row (IPVM public URL).
--            §11 #11 amendment-log discipline — sibling to the MAC-525 / MAC-
--                  533 ratification block in operator_review/.
--            §11 #17 notes JSON discipline — every new INSERT uses
--                  json_object(...); no text-suffix concat; the 3 UPDATE
--                  targets' notes are not touched.
--
-- Companion artifacts:
--   operator_review/MAC-533/ingest_plan.md  — per-brand spoke/alias/held/covered
--                                            table + counts + provenance
--   operator_review/MAC-533/apply_proof.md  — backup sha + rc + before/after
--                                            counts + 5+ spot-checks + set-
--                                            equality between plan and land
--   operator_review/MAC-525/ratification.md — CTO ratification (binding)
--   extraction_outputs/mac525_ipvm/oem_aliases.csv — 140-row source list
--   extraction_outputs/mac525_ipvm/vendor_leads.csv — 267→242 leads (HOLD)
-- ============================================================================

BEGIN TRANSACTION;

-- ---- Strict pre-condition guard (all-or-nothing) --------------------------
-- Aborts the whole transaction unless the world is exactly as expected at
-- apply time. CHECK(ok=1) on the TEMP table → rolling back on any failure.
CREATE TEMP TABLE _mig0041_pre (ok INTEGER CHECK (ok = 1));

-- (a) Hubs present + not arm rows
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE id IN (208, 209, 255)
       AND is_arm = 0
       AND parent_manufacturer_id IS NULL
       AND query_default = 'visible'
) = 3 THEN 1 ELSE 0 END;

-- (b) The 3 already-covered UPDATE targets present and parent_manufacturer_id IS NULL
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE id IN (298, 303, 308)
       AND parent_manufacturer_id IS NULL
) = 3 THEN 1 ELSE 0 END;

-- (c) No manufacturer row currently has parent_manufacturer_id pointing at our 3 hubs
--     (re-apply safety: 2nd run must abort, not double-write; also confirms the
--      "leave Speco" call hasn't been done by another migration in the meantime)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE parent_manufacturer_id IN (208, 209, 255)
) = 0 THEN 1 ELSE 0 END;

-- (d) Hikvision aliases does not yet contain any of the 6 new tokens
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE id = 209
       AND (
         aliases LIKE '%EZVIZ%' COLLATE NOCASE OR
         aliases LIKE '%HiLook%' COLLATE NOCASE OR
         aliases LIKE '%Hikmicro%' COLLATE NOCASE OR
         aliases LIKE '%HiWatch%' COLLATE NOCASE OR
         aliases LIKE '%Annke%' COLLATE NOCASE OR
         aliases LIKE '%LaView%' COLLATE NOCASE
       )
) = 0 THEN 1 ELSE 0 END;

-- (e) No sources row matches the IPVM public directory URL yet (re-apply safety)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM sources
     WHERE url = 'https://ipvm.com/reports/hikvision-oem-directory'
        OR url LIKE 'https://ipvm.com/reports/%'
) = 0 THEN 1 ELSE 0 END;

-- (f) schema_version = 33 (data-only, no DDL)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT MAX(version) FROM schema_version
) = 33 THEN 1 ELSE 0 END;

-- (g) json_valid(notes) = 1 on the 3 UPDATE targets (pre-flight confirmed)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE id IN (298, 303, 308) AND json_valid(notes) = 1
) = 3 THEN 1 ELSE 0 END;

-- (h) Exactly 156 manufacturer rows pre-migration (baseline; +84 = 240)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
) = 156 THEN 1 ELSE 0 END;

-- (i) Exactly 97 sources rows pre-migration (+1 = 98)
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM sources
) = 97 THEN 1 ELSE 0 END;

-- (j) Identifiers count baseline (regression catch — must be UNCHANGED)
--     identifiers total = 43848, identifiers active = 43132
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM identifiers
) = 43848 THEN 1 ELSE 0 END;
INSERT INTO _mig0041_pre(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM identifiers WHERE superseded_by IS NULL
) = 43116 THEN 1 ELSE 0 END;

-- ---- The one sources row for IPVM public directory -------------------------
-- source_type='crowdsourced' — existing CHECK-enum value (same slot as
-- FoggedLens/identification-catalog id=104 and fccid.io id=51 — third-party
-- public-attribution catalog). NO new enum value, NO DDL.
INSERT INTO sources (name, url, source_type, tier, notes)
VALUES (
    'IPVM — Public Camera & VMS Directory (Hikvision/Dahua OEM map + profile/VMS/discovery)',
    'https://ipvm.com/reports/hikvision-oem-directory',
    'crowdsourced',
    3,
    json_object(
        'admission_basis', 'MAC-525 IPVM public-directory cohort; CTO ratified per operator_review/MAC-525/ratification.md',
        'dispatch_ref', 'MAC-533',
        'public_marker_seen_verbatim', 'PUBLIC - This article does not require an IPVM subscription. Feel free to share.',
        'harvested_directories', 'https://ipvm.com/reports/hikvision-oem-directory | https://ipvm.com/reports/dahua-oem | https://ipvm.com/reports/profile-directory | https://ipvm.com/reports/camera-discovery-tools | https://ipvm.com/reports/vms-directory',
        'paywalled_honest_zero', 'https://ipvm.com/reports/uniview-oem | https://ipvm.com/reports/va-directory | https://ipvm.com/reports/ndaa-compliant-list (body masked with [Restricted] asterisks + [Premium Content Image] placeholders; no PUBLIC marker; no bypass attempted)',
        'yield_type', 'OEM-alias -> parent-OEM brand attribution + vendor-name leads; NO MAC OUIs / BLE IDs / hardcoded identifiers (IPVM publishes none)',
        'export_impact', 'ZERO — manufacturer-attribution metadata only (aliases / parent_manufacturer_id); zero net-new identifier values per MAC-525 ratification',
        'tier_rationale', '3 — community-maintained secondary attribution source; below official/regulatory tier 1-2; above unverified inferred tier 4'
    )
);

-- ---- Already-covered UPDATEs (Amcrest + Lorex → Dahua 208) -----------------
-- Speco (id=308) is intentionally NOT touched — MAC-525 ratification §"HOLD"
-- explicitly names Speco as a major independent brand that must NOT be auto-
-- attributed to Dahua (its IPVM listing is Dahua former/removed).
UPDATE manufacturers SET parent_manufacturer_id = 208
 WHERE id = 298 AND parent_manufacturer_id IS NULL;
UPDATE manufacturers SET parent_manufacturer_id = 208
 WHERE id = 303 AND parent_manufacturer_id IS NULL;

-- ---- Hikvision 209 aliases append (6 tokens; CP23 comma-string discipline) -
-- Append semantics: aliases = CASE WHEN aliases IS NULL OR aliases = ''
-- THEN ? ELSE aliases || ',' || ? END
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'EZVIZ'
  ELSE aliases || ',EZVIZ' END
 WHERE id = 209;
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'HiLook'
  ELSE aliases || ',HiLook' END
 WHERE id = 209;
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'Hikmicro'
  ELSE aliases || ',Hikmicro' END
 WHERE id = 209;
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'HiWatch'
  ELSE aliases || ',HiWatch' END
 WHERE id = 209;
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'Annke'
  ELSE aliases || ',Annke' END
 WHERE id = 209;
UPDATE manufacturers SET aliases = CASE
  WHEN aliases IS NULL OR aliases = '' THEN 'LaView'
  ELSE aliases || ',LaView' END
 WHERE id = 209;

-- ---- Hikvision 209 SPOKE inserts (52 rows) --------------------------------
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('ABUS', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'ABUS', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Acegear', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Acegear', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('AGM Global Vision', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'AGM Global Vision', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Alula', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Alula', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Arcdyn', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Arcdyn', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Aritech', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Aritech (Carrier)', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'Carrier'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Aukoo Technology', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Aukoo Technology', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('CCTV Direct', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'CCTV Direct', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Cantek', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Cantek', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Covert Security', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Covert Security', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Detec', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Detec', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('DMP', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'DMP (video doorbell only)', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'video doorbell only'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('DSS', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'DSS', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Dunlop', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Dunlop', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('ENS', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'ENS', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Epcom', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Epcom', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Eyesonic', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Eyesonic', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Global Network Security', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Global Network Security', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Grundig', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Grundig', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('GSS', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'GSS', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hinovision', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Hinovision', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hitachi', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Hitachi', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hitosino', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Hitosino', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hunt CCTV', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Hunt CCTV', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hyundai Security', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Hyundai Security', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Inkovideo', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Inkovideo', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Jetview', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Jetview', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('JFL', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'JFL', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Jlinks', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Jlinks', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Koa/KarbonVision', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Koa/KarbonVision', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'dual-name brand'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('LTS', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'LTS', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Mercury Security and Facilities Management', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Mercury Security and Facilities Management', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Nodac', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Nodac', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Novicam', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Novicam', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('NSI Distribution', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'NSI Distribution', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Oculur / A1 Security Cameras', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Oculur / A1 Security Cameras', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'dual-name brand'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Paxton', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Paxton', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Pnet', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Pnet', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Power Technology', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Power Technology', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Purpose AV', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Purpose AV', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Raster', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Raster', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('RVi', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'RVi', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Scati', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Scati', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Security System Depot', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Security System Depot', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('SecurityTronix', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'SecurityTronix', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Siqura / TKH', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Siqura / TKH', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'TKH Security'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Technomate', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Technomate', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('U-Spy Store', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'U-Spy Store', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('UnixCCTV', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'UnixCCTV', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Vantage Security', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Vantage Security', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Winic', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Winic', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'cross_parent_note', 'Brand also appears in Dahua current/former IPVM listing; Hikvision current attribution selected per ingest_plan.md cross-parent duplicate rule'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Zicom', NULL, NULL, 'https://ipvm.com/reports/hikvision-oem-directory', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'hikvision-oem-directory', 'ipvm_cite_line', 'Zicom', 'ipvm_source_url', 'https://ipvm.com/reports/hikvision-oem-directory', 'hub_relationship', 'Independent firm sourcing Hikvision OEM line per IPVM public-directory attestation; hub = Hikvision (id=209). Cross-parent duplicates (annke/cantek/ens/gss/raster/rvi/securitytronix/winic) attributed ONCE under the Hikvision current listing per ingest_plan.md section 1.A.2.', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 209, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Activecam', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Activecam', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Ameta', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Ameta', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Ascendent', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Ascendent', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Backstreet Surveillance', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Backstreet Surveillance', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Bosch', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Bosch', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('CCTV Security Pros', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'CCTV Security Pros', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('CP Plus', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'CP Plus (Orange Line)', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'Orange Line'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('eLine', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'eLine', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Gess Technologies', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Gess Technologies', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Hiltron', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Hiltron', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('IC Realtime', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'IC Realtime', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Ikegami', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Ikegami', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Inaxsys', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Inaxsys', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Infinity CCTV', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Infinity CCTV', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Innekt', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Innekt', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Intelbras', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Intelbras', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('KBVision', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'KBVision', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Maxron', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Maxron', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Montavue', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Montavue', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Oco', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Oco', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Optiview', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Optiview', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Packetalk', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Packetalk', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('People Fu', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'People Fu', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('PlatinumCCTV', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'PlatinumCCTV', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Qube', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Qube', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Security Camera King', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Security Camera King (Elite series)', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'Elite series'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Sectec', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Sectec', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('ToughDog', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'ToughDog', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Unisight', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Unisight (EmPower)', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors', 'product_line_scope', 'EmPower'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('VIP Vision', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'VIP Vision', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Watchnet', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Watchnet', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');
INSERT INTO manufacturers (canonical_name, aliases, primary_category, source_url, notes, parent_manufacturer_id, is_arm, query_default) VALUES ('Zuum', NULL, NULL, 'https://ipvm.com/reports/dahua-oem', json_object('ipvm_admission_basis', 'MAC-525 IPVM public-directory cohort; ratified by CTO per operator_review/MAC-525/ratification.md', 'ipvm_dispatch_ref', 'MAC-533', 'ipvm_directory', 'dahua-oem-current', 'ipvm_cite_line', 'Zuum', 'ipvm_source_url', 'https://ipvm.com/reports/dahua-oem', 'hub_relationship', 'Independent firm sourcing Dahua OEM line per IPVM public-directory attestation; hub = Dahua (id=208).', 'query_visibility_rationale', 'hidden_arm so default manufacturer queries (WHERE query_default = ''visible'') do not surface arm rows for non-hub vendors'), 208, 1, 'hidden_arm');

-- ---- Strict post-condition guard (all-or-nothing) -------------------------
CREATE TEMP TABLE _mig0041_post (ok INTEGER CHECK (ok = 1));

-- (a) manufacturers count = 156 + 84 = 240
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
) = 240 THEN 1 ELSE 0 END;

-- (b) sources count = 97 + 1 = 98
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM sources
) = 98 THEN 1 ELSE 0 END;

-- (c) Hikvision 209 aliases contains all 6 new tokens (case-insensitive)
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE id = 209
       AND aliases LIKE '%EZVIZ%' COLLATE NOCASE
       AND aliases LIKE '%HiLook%' COLLATE NOCASE
       AND aliases LIKE '%Hikmicro%' COLLATE NOCASE
       AND aliases LIKE '%HiWatch%' COLLATE NOCASE
       AND aliases LIKE '%Annke%' COLLATE NOCASE
       AND aliases LIKE '%LaView%' COLLATE NOCASE
) = 1 THEN 1 ELSE 0 END;

-- (d) Amcrest (298) + Lorex (303) parent = 208; Speco (308) parent IS NULL
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE (id = 298 AND parent_manufacturer_id = 208)
        OR (id = 303 AND parent_manufacturer_id = 208)
        OR (id = 308 AND parent_manufacturer_id IS NULL)
) = 3 THEN 1 ELSE 0 END;

-- (e) Exactly 52 new SPOKE rows under Hikvision 209
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE parent_manufacturer_id = 209
       AND is_arm = 1
       AND query_default = 'hidden_arm'
       AND json_extract(notes, '$.ipvm_dispatch_ref') = 'MAC-533'
) = 52 THEN 1 ELSE 0 END;

-- (f) Exactly 32 new SPOKE rows under Dahua 208
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers
     WHERE parent_manufacturer_id = 208
       AND is_arm = 1
       AND query_default = 'hidden_arm'
       AND json_extract(notes, '$.ipvm_dispatch_ref') = 'MAC-533'
) = 32 THEN 1 ELSE 0 END;

-- (g) Identifiers UNCHANGED — total 43848, active 43132
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM identifiers
) = 43848 THEN 1 ELSE 0 END;
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM identifiers WHERE superseded_by IS NULL
) = 43116 THEN 1 ELSE 0 END;

-- (h) Exactly one new sources row (the IPVM one) — verify url uniqueness
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM sources
     WHERE url = 'https://ipvm.com/reports/hikvision-oem-directory'
) = 1 THEN 1 ELSE 0 END;

-- (i) schema_version stays at 33 (data-only migration; no version bump)
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT MAX(version) FROM schema_version
) = 33 THEN 1 ELSE 0 END;

-- (j) FK integrity post-check — verify every MAC-533 spoke row's parent_manufacturer_id points at a real hub
--     (json_valid filter first to skip pre-existing rows with malformed-JSON notes — §11 #17 precedent)
INSERT INTO _mig0041_post(ok) SELECT CASE WHEN (
    SELECT COUNT(*) FROM manufacturers m
     WHERE json_valid(m.notes) = 1
       AND m.is_arm = 1
       AND m.query_default = 'hidden_arm'
       AND json_extract(m.notes, '$.ipvm_dispatch_ref') = 'MAC-533'
       AND NOT EXISTS (
         SELECT 1 FROM manufacturers h
          WHERE h.id = m.parent_manufacturer_id
            AND h.is_arm = 0
            AND h.query_default = 'visible'
       )
) = 0 THEN 1 ELSE 0 END;

DROP TABLE _mig0041_pre;
DROP TABLE _mig0041_post;

COMMIT;
