"""MAC-411 — Cohort 6 (Pet / kid cellular tracker) extraction tests.

Proves candidates.json is regenerated byte-identical from the on-disk raw
artifacts (4 companion APKs + IEEE oui.csv), that every promoted UUID is
byte-faithful in its pinned dex + net-new in the live DB (mode=ro), that the
FP-triage is complete (every contested UUID has a cited co-located class), that
the hard guards hold (Tile cross-vendor; ble_company_id=0), and that §11 #7
(<=200-char excerpt) is app-enforced.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from db.sources import cohort6_petkid as c6  # noqa: E402

RAW_PRESENT = all((REPO / a["rel_path"]).exists() for a in c6.APKS.values()) and \
    (REPO / c6.A_OUI).exists()
needs_raw = pytest.mark.skipif(not RAW_PRESENT, reason="gitignored raw APKs/registry not on disk")


# --- §11 #7 excerpt <=200 enforcement (positive + negative, no raw needed) -----
def test_clip_truncates_long():
    long = "x" * 500
    out = c6.clip(long)
    assert len(out) <= c6.MAX_EXCERPT
    assert out.endswith("…")


def test_clip_keeps_short():
    assert c6.clip("  short value  ") == "short value"


def test_source_row_key_deterministic():
    a = c6.source_row_key("u", "ble_service_uuid", "0000fa25-...")
    b = c6.source_row_key("u", "ble_service_uuid", "0000fa25-...")
    assert a == b and len(a) == 64


def test_person_pii_redaction():
    clean, n = c6.redact_person_pii("Contact John Smith at HQ")
    assert n == 1 and "[REDACTED_PERSON]" in clean
    clean0, n0 = c6.redact_person_pii("Whistle Labs, Inc., 251 Rhode Island Street")
    assert n0 == 0


# --- determinism + cite-faithfulness (need raw on disk) -----------------------
@needs_raw
def test_apk_sha256_pins_hold():
    for a in c6.APKS.values():
        assert c6.file_sha256(a["rel_path"]) == a["sha256"]


@needs_raw
def test_build_deterministic_byte_identical():
    a = json.dumps(c6.build(), indent=2, ensure_ascii=False, sort_keys=True)
    b = json.dumps(c6.build(), indent=2, ensure_ascii=False, sort_keys=True)
    assert a == b


@needs_raw
def test_candidates_json_matches_module_output():
    out = REPO / "extraction_outputs" / "mac393_c6_petkid" / "candidates.json"
    on_disk = out.read_text(encoding="utf-8")
    regenerated = json.dumps(c6.build(), indent=2, ensure_ascii=False) + "\n"
    assert on_disk == regenerated, "candidates.json is stale — re-run the module"


@needs_raw
def test_counts_and_delta():
    p = c6.build()
    c = p["counts"]
    assert c["ble_service_uuid_promote"] == 53
    assert c["  fi"] == 23 and c["  jiobit"] == 10 and c["  whistle"] == 20
    assert c["  whistle_singletons_resolved_to_vendor"] == 5
    assert c["extraction_delta_vs_harvest"] == 5
    assert c["oui_promote"] == 1 and c["ble_local_name_bonus"] == 5
    assert c["ble_company_id_net_new"] == 0


@needs_raw
def test_every_promoted_uuid_is_byte_faithful_and_bounded():
    p = c6.build()
    scans = {v: c6.scan_uuids(v) for v in c6.APKS}
    vmap = {"Fi (Barking Labs Corp)": "fi", "Jiobit (Life360, Inc.)": "jiobit",
            "Whistle Labs, Inc. (Mars Petcare)": "whistle"}
    for cand in p["candidates"]:
        vend = vmap[cand["manufacturer"]]
        u = cand["identifier"]
        assert u in scans[vend], f"{u} not in {vend} dex"
        # excerpt is the verbatim dex byte-form (case preserved), <=200 chars
        assert cand["source_markers"]["byte_form"].lower() == u
        assert len(cand["source_markers"]["excerpt"]) <= c6.MAX_EXCERPT


@needs_raw
def test_all_promoted_are_net_new():
    p = c6.build()
    import sqlite3
    conn = sqlite3.connect(f"file:{c6.DB}?mode=ro", uri=True)
    for cand in p["candidates"] + [p["oui_candidate"]] + p["ble_local_name_bonus"]:
        assert cand["net_new"] is True, f"{cand['identifier']} not net-new"
        assert not c6.already_in_db(conn, cand["identifier"])
    conn.close()


# --- FP-triage completeness + the corrected dispositions ----------------------
@needs_raw
def test_angelsense_two_uuids_excluded_as_salesforce_library():
    p = c6.build()
    ang = [e for e in p["excluded"] if e["manufacturer"] == "AngelSense"]
    assert len(ang) == 2
    for e in ang:
        assert e["reason"] == "non_ble_library"
        assert "salesforce/marketingcloud" in e["detail"] or "Salesforce" in e["detail"]
        assert "salesforce" in e["source_markers"]["dex_member"].lower()


@needs_raw
def test_whistle_appcenter_secret_excluded_not_ble():
    p = c6.build()
    ac = [e for e in p["excluded"]
          if e["identifier"].startswith("ec6e18c5")]
    assert len(ac) == 1 and ac[0]["reason"] == "non_ble_sdk_config"
    assert "APP_CENTER_APP_SECRET" in ac[0]["detail"]
    # the labeled SDK secret value is masked (never committed in full)
    assert ac[0]["value_redacted"] is True
    assert "****" in ac[0]["identifier"]
    assert "****" in ac[0]["source_markers"]["byte_form"]
    assert p["_meta"]["secret_redaction_count"] == 1


@needs_raw
def test_no_full_appcenter_secret_in_serialized_output():
    """The full App Center secret value must not appear anywhere in candidates.json."""
    out = REPO / "extraction_outputs" / "mac393_c6_petkid" / "candidates.json"
    txt = out.read_text(encoding="utf-8")
    assert "ec6e18c5-7f14-4bdf-9c95-9ead4ebd90f8" not in txt


@needs_raw
def test_whistle_sdp_uuid_flagged_not_promoted():
    p = c6.build()
    assert len(p["flagged_ambiguous"]) == 1
    f = p["flagged_ambiguous"][0]
    assert f["identifier"].startswith("6cdc3b69")
    assert f["notes"]["transport"] == "bluetooth_classic_sdp"
    assert f["confidence"] == 40
    # NOT in the promote set
    assert f["identifier"] not in {c["identifier"] for c in p["candidates"]}


@needs_raw
def test_five_spple_singletons_resolved_to_vendor_promote():
    p = c6.build()
    resolved = [c for c in p["candidates"]
                if c["notes"].get("harvest_singleton_resolved_to_vendor")]
    assert len(resolved) == 5
    fields = {c["notes"]["wcconstants_field"] for c in resolved}
    assert "UUID_SERVICE_SPPLE" in fields
    assert all(c["confidence"] <= c["band_ceiling"] <= 75 for c in resolved)


@needs_raw
def test_whistle_service_vs_characteristic_resolved():
    p = c6.build()
    wh = [c for c in p["candidates"] if c["manufacturer"].startswith("Whistle")]
    roles = {c["notes"]["gatt_role"] for c in wh}
    assert {"service", "characteristic"} <= roles
    services = [c for c in wh if c["notes"]["gatt_role"] == "service"]
    assert len(services) == 2  # AMDTP service + SPPLE service


# --- hard guards --------------------------------------------------------------
@needs_raw
def test_tile_held_cross_vendor_never_promoted():
    p = c6.build()
    assert len(p["tile_held_cross_vendor"]) == 2
    promoted = {c["identifier"] for c in p["candidates"]}
    for t in p["tile_held_cross_vendor"]:
        assert t["identifier"] not in promoted
        assert t["held_db_rows"], "Tile UUID expected HELD in DB"
        assert t["present_in_jiobit_dex"] is True


@needs_raw
def test_ble_company_id_zero_apple_excluded():
    p = c6.build()
    f = p["ble_company_id_finding"]
    assert f["net_new"] == 0
    assert "0x4c" in f["evidence"]
    assert "Apple" in f["disposition"]


@needs_raw
def test_fp_magnets_not_promoted():
    p = c6.build()
    promoted = {c["identifier"] for c in p["candidates"]}
    for m in p["fp_magnet_audit"]:
        assert m["promoted"] is False
        assert m["identifier"] not in promoted


@needs_raw
def test_oui_whistle_labs_clean_netnew():
    p = c6.build()
    o = p["oui_candidate"]
    assert o["identifier"] == "e0:7c:62"
    assert o["manufacturer"] == "Whistle Labs, Inc."
    assert o["confidence"] == 85 and o["net_new"] is True
    assert "Whistle Labs, Inc." in o["source_markers"]["excerpt"]


@needs_raw
def test_all_candidates_proposed_gps_tracker_with_subtype():
    p = c6.build()
    for cand in p["candidates"] + [p["oui_candidate"]] + p["ble_local_name_bonus"]:
        assert cand["device_category"] == "gps_tracker"
        assert cand["notes"]["subtype"] == "pet_kid_cellular"
        assert cand["notes"]["category_pending_board_ratification"] is True
