"""MAC-403 — Cohort 3 (Bluetooth tracker) extraction tests.

Proves candidates.json is regenerated byte-identical from the on-disk raw
artifacts (SIG yaml + AirGuard .kt + the two CTO-authorized APKs), that every
cite-paste is verbatim, that §11 #7 (<=200 char excerpt) is app-enforced
(positive + negative), and that the key extraction verdicts hold.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO))

from db.sources import cohort3_bletracker as c3  # noqa: E402

RAW_PRESENT = (REPO / c3.A_AIRGUARD_PB).exists() and (REPO / c3.APK_PEBBLEBEE["artifact"]).exists()
needs_raw = pytest.mark.skipif(not RAW_PRESENT, reason="gitignored raw artifacts/APKs not on disk")


# --- §4.3 canonicalization -------------------------------------------------
def test_canon_uuid_16bit():
    assert c3.canon_uuid("0xFA25") == "0000fa25-0000-1000-8000-00805f9b34fb"
    assert c3.canon_uuid("0x2C02") == "00002c02-0000-1000-8000-00805f9b34fb"


def test_canon_uuid_rejects_garbage():
    with pytest.raises(ValueError):
        c3.canon_uuid("not-a-uuid")


# --- §11 #7 excerpt <=200 enforcement (positive + negative) ----------------
def test_excerpt_truncation_negative(tmp_path):
    """A >200-char source line is truncated with a marker (never emitted raw)."""
    f = tmp_path / "long.txt"
    long_line = "TOKEN " + "x" * 500
    f.write_text(long_line, encoding="utf-8")
    c3._file_cache[str(f.relative_to(c3.REPO)) if str(f).startswith(str(c3.REPO)) else str(f)] = [long_line]
    # locate reads via REPO-relative; emulate by direct cache injection under a rel key
    rel = "tmp_long_test_artifact.txt"
    c3._file_cache[rel] = [long_line]
    line, excerpt = c3.locate(rel, "TOKEN")
    assert line == 1
    assert len(excerpt) <= c3.MAX_EXCERPT
    assert excerpt.endswith("…")


def test_excerpt_short_positive():
    rel = "tmp_short_test_artifact.txt"
    c3._file_cache[rel] = ["short TOKEN line"]
    line, excerpt = c3.locate(rel, "TOKEN")
    assert excerpt == "short TOKEN line"
    assert len(excerpt) <= c3.MAX_EXCERPT


def test_locate_raises_on_absent_token():
    rel = "tmp_absent_test_artifact.txt"
    c3._file_cache[rel] = ["nothing here"]
    with pytest.raises(ValueError):
        c3.locate(rel, "MISSING_TOKEN")


# --- determinism + cite-faithfulness (need raw on disk) --------------------
@needs_raw
def test_build_deterministic_byte_identical():
    a = json.dumps(c3.build(), indent=2, ensure_ascii=False, sort_keys=True)
    b = json.dumps(c3.build(), indent=2, ensure_ascii=False, sort_keys=True)
    assert a == b


@needs_raw
def test_candidates_json_matches_module_output():
    out = REPO / "extraction_outputs" / "mac393_c3_bletracker" / "candidates.json"
    on_disk = out.read_text(encoding="utf-8")
    regenerated = json.dumps(c3.build(), indent=2, ensure_ascii=False) + "\n"
    assert on_disk == regenerated, "candidates.json is stale — re-run the module"


@needs_raw
def test_every_candidate_excerpt_is_verbatim_and_bounded():
    payload = c3.build()
    for cand in payload["candidates"]:
        m = cand["source_markers"]
        full = "\n".join(c3._lines(m["artifact"]))
        assert m["excerpt"].rstrip("…") in full, f"excerpt not in {m['artifact']}"
        assert len(m["excerpt"]) <= c3.MAX_EXCERPT


@needs_raw
def test_pebblebee_fa25_is_the_single_candidate_netnew_uncorroborated():
    payload = c3.build()
    assert len(payload["candidates"]) == 1
    cand = payload["candidates"][0]
    assert cand["value"] == "0000fa25-0000-1000-8000-00805f9b34fb"
    assert cand["identifier_type"] == "ble_service_uuid"
    assert cand["device_category"] == "bluetooth_tracker"
    assert cand["db_presence"] == "net-new"
    assert cand["confidence"] <= cand["band_ceiling"] <= 75
    # APK enrichment came up empty -> no lift
    assert payload["apk_enrichment"]["pebblebee"]["fa25_present_in_app_dex"] is False


@needs_raw
def test_cube_03ee_absent_no_recat():
    payload = c3.build()
    cube = payload["apk_enrichment"]["cube"]
    assert cube["company_id_03ee_present_in_app"] is False
    assert cube["is_cube_tracker_product"] is True
    assert cube["is_nbiot_cellular_tracker"] is True
    # no Cube candidate of any kind
    assert not any(c["manufacturer"] == "Cube" for c in payload["candidates"])


@needs_raw
def test_apk_sha256_pins_hold():
    for spec in (c3.APK_PEBBLEBEE, c3.APK_CUBE):
        assert c3.file_sha256(spec["artifact"]) == spec["sha256"]


@needs_raw
def test_tagfinder_fabrications_rejected_with_sig_contradiction():
    payload = c3.build()
    assert len(payload["rejected_fabrications"]) == 2
    for r in payload["rejected_fabrications"]:
        assert r["disposition"].startswith("REJECTED")
        assert r["sig_authority"]["excerpt"].startswith("- value:")
